# ==============================================================================
# 媒体分类字典配置
# 用于根据 TMDB 信息自动分类媒体文件
# ==============================================================================


# ==============================================================================
# 变量参考 (TMDB & ISO 标准)
# ==============================================================================

# -------------------- TMDB 电影类型 (Genre IDs) --------------------
# 28: 动作 (Action)
# 12: 冒险 (Adventure)
# 16: 动画 (Animation)
# 35: 喜剧 (Comedy)
# 80: 犯罪 (Crime)
# 99: 纪录片 (Documentary)
# 18: 剧情 (Drama)
# 10751: 家庭 (Family)
# 14: 奇幻 (Fantasy)
# 36: 历史 (History)
# 27: 恐怖 (Horror)
# 10402: 音乐 (Music)
# 9648: 悬疑 (Mystery)
# 10749: 爱情 (Romance)
# 878: 科幻 (Science Fiction)
# 10770: 电视电影 (TV Movie)
# 53: 惊悚 (Thriller)
# 10752: 战争 (War)
# 37: 西部 (Western)

# -------------------- TMDB 电视剧类型 (Genre IDs) --------------------
# 10759: 动作与冒险 (Action & Adventure)
# 16: 动画 (Animation)
# 35: 喜剧 (Comedy)
# 80: 犯罪 (Crime)
# 99: 纪录片 (Documentary)
# 18: 剧情 (Drama)
# 10751: 家庭 (Family)
# 10762: 儿童 (Kids)
# 9648: 悬疑 (Mystery)
# 10763: 新闻 (News)
# 10764: 真人秀 (Reality)
# 10765: 科幻与奇幻 (Sci-Fi & Fantasy)
# 10766: 肥皂剧 (Soap)
# 10767: 脱口秀 (Talk)
# 10768: 战争与政治 (War & Politics)
# 37: 西部 (Western)

# -------------------- ISO 3166-1 地区代码 (部分常用) --------------------
# 亚洲:
# CN: 中国大陆, HK: 中国香港, TW: 中国台湾, MO: 中国澳门
# JP: 日本, KR: 韩国, KP: 朝鲜
# TH: 泰国, VN: 越南, SG: 新加坡, IN: 印度, MY: 马来西亚, PH: 菲律宾, ID: 印度尼西亚

# 北美:
# US: 美国, CA: 加拿大, MX: 墨西哥

# 欧洲:
# GB: 英国, FR: 法国, DE: 德国, IT: 意大利, ES: 西班牙
# RU: 俄罗斯, NL: 荷兰, SE: 瑞典, NO: 挪威, FI: 芬兰, DK: 丹麦
# PT: 葡萄牙, IE: 爱尔兰, CH: 瑞士, AT: 奥地利, BE: 比利时, PL: 波兰

# 大洋洲/其他:
# AU: 澳大利亚, NZ: 新西兰, BR: 巴西, AR: 阿根廷


# ==============================================================================
# 高级分类规则 (基于高级变量)
# 字段说明:
#   genre_ids: TMDB 类型 ID (逗号分隔)
#   origin_country: 来源国家/地区代码 (逗号分隔)
#   original_language: 原始语言 (逗号分隔)
# ==============================================================================

advanced_rules:
  
  # -------------------- 电影分类策略 (Movie) --------------------
  movie:
    # --- 特殊分类 (优先) ---
    动画电影:
      genre_ids: '16'
    纪录片:
      genre_ids: '99'
    电视电影:
      genre_ids: '10770'
    
    # --- 按语种/地区 ---
    华语电影:
      original_language: 'zh,cn,bo,za'
      origin_country: 'CN,HK,TW,MO'
    
    # --- 按类型 (Genre IDs) ---
    科幻电影:
      genre_ids: '878'
    动作电影:
      genre_ids: '28'
    喜剧电影:
      genre_ids: '35'
    犯罪电影:
      genre_ids: '80'
    恐怖电影:
      genre_ids: '27'
    爱情电影:
      genre_ids: '10749'
    战争电影:
      genre_ids: '10752'
    惊悚电影:
      genre_ids: '53'
    奇幻电影:
      genre_ids: '14'
    音乐电影:
      genre_ids: '10402'
    历史电影:
      genre_ids: '36'
    西部电影:
      genre_ids: '37'
    家庭电影:
      genre_ids: '10751'
    冒险电影:
      genre_ids: '12'
    剧情电影:
      genre_ids: '18'
    悬疑电影:
      genre_ids: '9648'
    
    # --- 默认兜底 ---
    外语电影:
      default: true

  # -------------------- 电视剧分类策略 (TV) --------------------
  tv:
    # --- 动漫细分 (Genre ID 16) ---
    国漫:
      genre_ids: '16'
      origin_country: 'CN,HK,TW,MO'
    日番:
      genre_ids: '16'
      origin_country: 'JP'
    欧美动漫:
      genre_ids: '16'
      origin_country: 'US,CA,GB,FR,DE,IT,ES,AU,NZ'
    # 其他地区的动漫归为普通动漫或默认
    动漫:
      genre_ids: '16'
    
    # --- 特殊类型 ---
    纪录片:
      genre_ids: '99'
    儿童:
      genre_ids: '10762'
    综艺:
      # 10764: 真人秀, 10767: 脱口秀
      genre_ids: '10764,10767'
    
    # --- 剧集类型细分 ---
    科幻奇幻剧:
      genre_ids: '10765'
    动作冒险剧:
      genre_ids: '10759'
    战争政治剧:
      genre_ids: '10768'
    犯罪剧:
      genre_ids: '80'
    肥皂剧:
      genre_ids: '10766'
    喜剧:
      genre_ids: '35'
    剧情:
      genre_ids: '18'
    
    # --- 按地区分类 (兜底策略) ---
    国产剧:
      origin_country: 'CN'
    港台剧:
      origin_country: 'HK,TW,MO'
    日韩剧:
      origin_country: 'JP,KP,KR,TH,VN,SG,IN'
    欧美剧:
      origin_country: 'US,CA,GB,FR,DE,IT,ES,RU,AU,NZ,SE,NO,FI,DK,NL,IE,CH,AT,BE,PL'
    
    # --- 默认兜底 ---
    其他剧集:
      default: true


# ==============================================================================
# 旧版简单映射 (兼容性保留) (可忽略)
# ==============================================================================

# -------------------- 电影类别映射 --------------------
movie_categories:
  Action: 动作电影
  Adventure: 冒险电影
  Animation: 动画电影
  Comedy: 喜剧电影
  Crime: 犯罪电影
  Documentary: 纪录片
  Drama: 剧情电影
  Family: 家庭电影
  Fantasy: 奇幻电影
  History: 历史电影
  Horror: 恐怖电影
  Music: 音乐电影
  Mystery: 悬疑电影
  Romance: 爱情电影
  Science Fiction: 科幻电影
  Thriller: 惊悚电影
  War: 战争电影
  Western: 西部电影
  TV Movie: 电视电影

# -------------------- 电视剧类别映射 --------------------
tv_categories:
  Animation: 动漫
  Documentary: 纪录片
  Reality: 真人秀
  Talk: 脱口秀
  News: 新闻
  Soap: 肥皂剧
  Kids: 儿童
  Action & Adventure: 动作冒险剧
  Comedy: 喜剧
  Crime: 犯罪剧
  Drama: 剧情
  Family: 家庭剧
  Mystery: 悬疑剧
  Sci-Fi & Fantasy: 科幻奇幻剧
  War & Politics: 战争政治剧
  Western: 西部剧

# -------------------- 地区分类映射 --------------------
region_categories:
  CN: 国产剧
  HK: 港台剧
  TW: 港台剧
  JP: 日韩剧
  KR: 日韩剧
  US: 欧美剧
  GB: 欧美剧
  CA: 欧美剧
  AU: 欧美剧
  FR: 欧美剧
  DE: 欧美剧
  IT: 欧美剧
  ES: 欧美剧

# -------------------- 动漫地区细分 --------------------
anime_region_categories:
  JP: 日本动漫
  CN: 国产动漫
  US: 欧美动画

# -------------------- 默认分类 --------------------
defaults:
  movie: 其他电影
  tv: 其他剧集


# ==============================================================================
# 目录结构示例
# ==============================================================================
# 媒体库根目录/
# ├── 电影/
# │   ├── 动作电影/
# │   │   └── 复仇者联盟 (2012)/
# │   ├── 科幻电影/
# │   ├── 动画电影/
# │   └── 外语电影/
# ├── 电视剧/
# │   ├── 国产剧/
# │   │   └── 庆余年 (2019)/
# │   ├── 欧美剧/
# │   ├── 日韩剧/
# │   ├── 国漫/
# │   ├── 日番/
# │   └── 其他剧集/
